
rules:
  gav: "uk.g.h:rules-kjar:1.0.0-SNAPSHOT"
  remote:
    metadata-uri: "https://nexus.example.com/repository/maven-snapshots/uk/g/h/rules-kjar/1.0.0-SNAPSHOT/maven-metadata.xml"
  scan:
    period-ms: 10000
  session:
    pool-size: 16
  repo:
    user: "${NEXUS_USER:}"
    pass: "${NEXUS_PASS:}"


# drools-app/src/main/resources/application.yml
rules:
  gav: "uk.g.h:rules-kjar:1.0.0-SNAPSHOT"  # <-- your real G:A:V
  scan:
    period-ms: 5000                        # poll every 5s for the demo
  scanner:
    mode: local-m2                         # <- use LocalMavenScanner (no HTTP)
  local:
    m2: ""                                 # blank = use ~/.m2/repository (or set absolute path)
  session:
    pool-size: 8

logging:
  level:
    uk.g.h.rules.reload: DEBUG             # optional: see what the scanner is doing
